package cn.xavier.hrm.constant;

public interface MQConstants {
    String  KILL_EXCHANGE_NAME_TOPIC = "KILL_EXCHANGE_NAME_TOPIC";
    String  KILL_QUEUE_NAME_ORDER = "KILL_QUEUE_NAME_ORDER";
    String  KILL_DELAY_QUEUE_NAME_ORDER = "KILL_DELAY_QUEUE_NAME_ORDER";
    String  KILL_DEATH_ROUTINGKEY_ORDER = "KILL_DEATH_ROUTINGKEY_ORDER";
    String  KILL_DEATH_QUEUE_NAME_ORDER = "KILL_DEATH_QUEUE_NAME_ORDER";
    String  KILL_PAY_RESULT_QUEUE_NAME = "KILL_PAY_RESULT_QUEUE_NAME";
    String  KILL_PAY_RESULT_ROUTINGKEY = "KILL_PAY_RESULT_ROUTINGKEY";
    String  KILL_DELAY_ROUTINGKEY_ORDER = "KILL_DELAY_ROUTINGKEY_ORDER";
    String  KILL_ROUTINGKEY_ORDER = "KILL_ROUTINGKEY_ORDER";

}
